version: '3.1'
services:
  api:
    build: ./
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    restart: always

  postgres:
    image: "postgres:latest"
    container_name: "postgres"
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=pass
      - POSTGRES_DB=db
    ports:
      - "54320:5432"
    volumes:
      - /data/db/postgres:/var/lib/postgresql/data